version: "3.9"

services:

  mongo:
    image: mongo:7
    container_name: hypesoft-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: hypesoft-api
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - Mongo__ConnectionString=mongodb://mongo:27017

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: hypesoft-frontend
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  mongo_data: